[package]
name = "el-node-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eigensdk-rs = { version = "0.0.1", git = "https://github.com/supernovahs/eigensdk-rs" }